# Generated by Django 3.1.5 on 2021-06-28 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210628_2140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votes',
            old_name='votes',
            new_name='vote',
        ),
    ]
