# Generated by Django 3.1.5 on 2021-06-13 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
