# Generated by Django 3.1.5 on 2021-06-14 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210614_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='responder',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
        migrations.AddField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(to='app.Answer'),
        ),
        migrations.AddField(
            model_name='user',
            name='topics',
            field=models.ManyToManyField(to='app.Topic'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
