# Generated by Django 3.1.5 on 2021-06-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210614_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='topics',
        ),
        migrations.AddField(
            model_name='answer',
            name='responder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to='app.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='app.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
