# Generated by Django 3.1.5 on 2021-06-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210616_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=models.ImageField(blank=True, height_field='300', null=True, upload_to='', width_field='300'),
        ),
    ]
