# Generated by Django 3.1.5 on 2021-06-16 18:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210616_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[35, 35], upload_to=''),
        ),
    ]
